let string_1 = document.getElementById("string-1")
let string_2 = document.getElementById("string-2")
let string_3 = document.getElementById("string-3")
let string_4 = document.getElementById("string-4")
let string_5 = document.getElementById("string-5")
let string_6 = document.getElementById("string-6")
console.log(string_3.textContent)
console.log(string_5.textContent)
console.log(string_2.textContent)
console.log(string_6.textContent)
console.log(string_4.textContent)
console.log(string_1.textContent)
